### ISSUE TITLE
balance tree leaf format

### ISSUE THREAD

**Issue by barryWhiteHat** [barryWhiteHat/RollupNC#14]
Here is a proposed format for balance tree leaves data storage. Where each an independent field element which keeps things simple and they are hashed together with mimc to make the field element which is included in the tree. 

`pubkey_x` 253 bits
`pubkey_y` 253 bits
`token` 253 bits
`balance` 253 bits
`nonce` 253 bits

**Comment by GuthL** [comment]
What about dropping pubkey_y from the account?

**Comment by barryWhiteHat** [comment]
Don't think its worth it because we need to do binary decompression to get the sign bit of the y coord. And that take a lot of constraints. Also not sure its worth the complexity.

With pedersen commitments the case for minimizing the y coord was quite strong. As each bit cost about 4 constraints. But with mimC that cost is considerably lower.

But these are just my thoghts at the moment. Could you give me some numbers on how much the binary to field element in circom costs? Mimc is 700 constraints?

**Comment by GuthL** [comment]
You don't have to do it. pubkey_x is unique no matter what. We can provide pubkey_y outside the leaf and verifying that the equation is verified. 
I even wonder if we need to verify the equation since we would use the y for the signature scheme.

**Comment by barryWhiteHat** [comment]
Every pubkey_x has two possibly pubkey_y. I think if you don't include the y point you halve the security of the signature scheme. Because every time you check for discrete log you only need to find an x point of which two exist.

**Comment by GuthL** [comment]
No, I think it is the other way around: every y has two possible x because of the squaring.

**Comment by barryWhiteHat** [comment]
You don't need to reverse y**2 you just need to find a point where x == x_search and then the y point is irrelevant. That means that the chance of finding this point is 2x because there are 2 points. Thus it halves the security.

**Comment by barryWhiteHat** [comment]
> Saving only x is enough because reversing y**2 is as hard as DLOG.

I don't think this is true https://github.com/barryWhiteHat/baby_jubjub_ecc/blob/master/tests/sapling_jubjub.py#L81

**Comment by GuthL** [comment]
You are indeed right! Let keep the two points 👍

**Comment by GuthL** [comment]
You are indeed right! Let keep the two points 👍

**Comment by therealyingtong** [comment]
Minor detail: our circuits currently have it in a slightly different order. This doesn't really matter, we just want to make sure we're getting the same result for multihash.
`pubkey_x`
`pubKey_y`
`balance`
`nonce`
`token`

**Comment by tspoff** [comment]
> Minor detail: our circuits currently have it in a slightly different order. This doesn't really matter, we just want to make sure we're getting the same result for multihash.
> `pubkey_x`
> `pubKey_y`
> `balance`
> `nonce`
> `token`

Ok, I can switch to this order in the contract

**Comment by therealyingtong** [comment]
oh actually. it turns out MiMC is commutative, so `hash(a, b) = hash(b, a) `. so it doesn't matter
