### ISSUE TITLE
Withdraw coins from snark side chain into smart contract

### ISSUE THREAD

**Issue by barryWhiteHat** [barryWhiteHat/RollupNC#3]
1. Create transaction to send coins to the zero address
2. Add batch of transactions to each snark. 
3. Creat a merkl proof of transaction in this batch. 
4. Prove that that transactions send coins to zero address. 
5. Validate a signature of the transfer of that coin that defines where the transfer should be sent. 
6. Allow that address to call the contract to withdraw this balance.

**Comment by barryWhiteHat** [comment]
https://github.com/barryWhiteHat/RollupNC/pull/28

**Comment by barryWhiteHat** [comment]
@therealyingtong can i close?

**Comment by therealyingtong** [comment]
@barryWhiteHat yup!
