### ISSUE TITLE
circuit transfers list of transactions as public input

### ISSUE THREAD

**Issue by barryWhiteHat** [barryWhiteHat/RollupNC#8]
We want to include a list of transactions `to`, `from`, `amount` , `token` as a merkle tree and pass that as a public input from the smart contract. 

This will help with https://github.com/barryWhiteHat/RollupNC/issues/3

Also it will allow us to do some
1. Instant finaltiy stuff where the operator signs a transaction will be included in block. Afterwards they can be challenged to prove it was included. If they don't prove inside a time limit they get slashed. 
2. State channels. Where the public key in the side chain is a multisig we can use this to do state updates. Then the withdraw to a dispute resolution multisig defined by the multisig at withdraw time.

**Comment by therealyingtong** [comment]
i'm going to close this issue since we already have a tx tree -- we have to add circuit transfer fees to it, which can be discussed on #10 .
